version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  default:

services:

  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring